import type { Metadata } from 'next'

import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

import { AppLayout } from '@/components/layouts/AppLayout'
import '@/utils/styles/globals.css'

export const metadata: Metadata = {
	title: 'Minyoung',
	description: 'Generated by create next app',
}

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode
}>) => {
	return (
		<html lang='en'>
			<head>
				<meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' />
			</head>
			<body className='antialiased'>
				<AppLayout>{children}</AppLayout>
				<ToastContainer
					position='top-center'
					autoClose={3000}
					hideProgressBar={false}
					newestOnTop
					closeOnClick
					rtl={false}
					pauseOnFocusLoss
					draggable
					pauseOnHover
					theme='colored'
				/>
			</body>
		</html>
	)
}

export default RootLayout
